CREATE TABLE city (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    isfavorite BOOLEAN NOT NULL DEFAULT FALSE,
    createdat TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);